[package]
name = "dv-dizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
y = { path = "../y" }
iot-dizer = { path = "../iot-dizer" }