[package]
name = "dv-oxi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
y = { path = "../y" }
x = { path = "../x" }
oxi = { path = "../lib-oxi" }